---
- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - python-simplejson
    - man
    - man-pages
    - vim-enhanced
    - sysstat
    - lsof
    - jwhois
    - telnet
    - nc

- name: Install ntp
  yum: name=ntp state=latest

- name: Make sure ntpd is stopped
  service: name=ntpd state=stopped

- name: Start ntpdate
  service: name=ntpdate state=started

- name: Start ntpd
  service: name=ntpd state=started enabled=yes
