---
- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - python-simplejson
    - man
    - man-pages
    - vim-enhanced
    - sysstat
    - lsof
    - jwhois
    - telnet
    - nc
    - ntp
    - parted
    - perl
    - iotop
    - links
    - unzip
    - curl
    - wget

- name: Disable yum excludes
  lineinfile: dest=/etc/yum.conf backrefs=yes regexp='^exclude=(.*)$' line='#exclude=\1'

- name: Update all packages
  yum: name=* state=latest

- name: Make sure ntpd is stopped
  service: name=ntpd state=stopped

- name: Start ntpdate
  service: name=ntpdate state=started

- name: Start ntpd
  service: name=ntpd state=started enabled=yes

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file"
              state=present
              line="{{ item }}"
  with_items:
    - "* soft nofile 32768"
    - "* hard nofile 32768"

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
              insertafter=EOF
              state=present
              line="{{ item }}"
              mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"

- name: Get number of kernels in grub.conf
  shell: grep -E "^[[:blank:]]*kernel" /boot/grub/grub.conf | grep -v transparent_hugepage
  register: grep_result
  ignore_errors: true

- name: Disable Transparent Huge Pages
  lineinfile: dest=/boot/grub/grub.conf
              backrefs=True
              state=present
              regexp='(^\s*kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.\,]+)*)\s*$'
              line='\1 transparent_hugepage=never'
  register: result
  with_items: grep_result.stdout_lines

- name: Disable Transparent Huge Pages until reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: true

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- include: iptables.yml
  when: cloud_nodes_count is defined and cloud_nodes_count > 0
