---
- name: "Build the environment"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create the SSH keypair
      local_action:
        module: rax_keypair
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "{{ cloud_config.ssh.keyname }}"
        public_key: "{{ lookup('file', cloud_config.ssh.keyfile) }}"
        region: "{{ cloud_config.rax_region }}"

    - name: Include kafka-nodes group variables
      include_vars: group_vars/kafka-nodes

    - name: "Create kafka nodes"
      local_action:
        module: rax
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "kafka-%02d.{{ cloud_config.domain }}"
        image: "{{ cloud_image }}"
        flavor: "{{ cloud_flavor }}"
        count: "{{ cloud_nodes_count }}"
        region: "{{ cloud_config.rax_region }}"
        key_name: "{{ cloud_config.ssh.keyname }}"
        exact_count: yes
        auto_increment: true
        group: kafka-nodes
        state: present
        wait: true
        wait_timeout: 900
      register: rax_kafka
      when: cloud_nodes_count > 0

    - name: "Create CBS Volumes for kafka nodes"
      local_action:
        module: rax_cbs
        credentials: "{{ cloud_config.rax_credentials_file }}"
        name: "{{ item[0].name }}_{{ item[1] }}"
        volume_type: "{{ cbs_disks_type }}"
        size: "{{ cbs_disks_size }}"
        region: "{{ cloud_config.rax_region }}"
        state: present
        wait: true
      with_nested:
        - rax_kafka.instances
        - data_disks_devices
      when: cloud_nodes_count > 0 and build_cbs

    - name: "Attach CBS Volumes to kafka nodes"
      local_action:
        module: rax_cbs_attachments
        credentials: "{{ cloud_config.rax_credentials_file }}"
        volume: "{{ item[0].name }}_{{ item[1] }}"
        server: "{{ item[0].id }}"
        region: "{{ cloud_config.rax_region }}"
        device: "/dev/{{ item[1] }}"
        state: present
        wait: true
      with_nested:
        - rax_kafka.instances
        - data_disks_devices
      when: cloud_nodes_count > 0 and build_cbs

- name: "Show debug info"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Show rax_kafka info"
      debug: var=rax_kafka
      when: debug
